import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowDown, Menu, X, Building2, HardHat, Ruler, Hammer, Check, Plus, Minus } from 'lucide-react';
import './style.css';

const photo = (id, width=1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const projects = [
 { name:'The Courtyard Residence', category:'Residential', image:'photo-1600585154340-be6161a56a0c', description:'A contemporary home that brings natural light, generous living spaces, and the outdoors together.' },
 { name:'The Urban Workspace', category:'Commercial', image:'photo-1486406146926-c627a92ad1ab', description:'An architectural direction for a modern workplace, with a confident facade and flexible spaces.' },
 { name:'A Fresh Perspective', category:'Renovation', image:'photo-1600210492486-724fe5c67fb0', description:'A warm, considered interior concept that reimagines existing space for everyday comfort.' },
];
const services=[{icon:Building2,title:'General Construction',text:'From the first foundation to the final finish. A coordinated approach to bringing your entire project to life.'},{icon:Ruler,title:'Design & Build',text:'One vision. One team. Thoughtful design and practical construction, working together from day one.'},{icon:HardHat,title:'Project Management',text:'Every detail accounted for. Clear planning, hands-on coordination, and communication at every stage.'},{icon:Hammer,title:'Renovation & Fit-Out',text:'New possibilities for existing spaces. Purposeful improvements that transform how you live and work.'}];
function Logo(){return <a className="logo" href="#home" aria-label="Shane Construction home"><span className="logo-mark"><i/><i/><i/></span><span>SHANE<small>CONSTRUCTION CORPORATION</small></span></a>}
function App(){
 const [menu,setMenu]=useState(false),[filter,setFilter]=useState('All projects'),[selected,setSelected]=useState(null),[faq,setFaq]=useState(0),[submitted,setSubmitted]=useState(false);
 const dialog=useRef(null),form=useRef(null);
 useEffect(()=>{if(selected){dialog.current.showModal();}else{dialog.current?.close();}},[selected]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[]);
 function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);const content=`SHANE CONSTRUCTION CORPORATION\nProject inquiry\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\nProject type: ${data.get('type')}\n\n${data.get('message')}\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='shane-project-inquiry.txt';a.click();URL.revokeObjectURL(url);setSubmitted(true);}
 return <><header><div className="nav-wrap"><Logo/><nav className={menu?'open':''}>{[['About us','about'],['Our services','services'],['Our projects','projects'],['Our process','process']].map(([label,id])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a className="button nav-cta" href="#contact">Let’s build together <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main><section className="hero" id="home"><img className="hero-image" src={photo('photo-1486406146926-c627a92ad1ab',2400)} alt="Dramatic view of contemporary architecture reaching toward the sky" fetchPriority="high"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow light"><span/>YOUR VISION. OUR FOUNDATION.</div><h1>Built with purpose.<br/>Built to <em>last.</em></h1><div className="hero-bottom"><p>More than structures. We build possibilities.<br/>Your partner in turning ambitious ideas into<br className="desktop-break"/> spaces that stand the test of time.</p><a href="#projects" className="button orange">Explore our work <ArrowUpRight size={20}/></a></div></div><div className="hero-foot"><span>SHANE CONSTRUCTION CORPORATION</span><a href="#about">SCROLL TO DISCOVER <ArrowDown size={15}/></a><span className="hero-coordinate">DESIGNED FOR LIFE. ENGINEERED FOR TOMORROW.</span></div><div className="hero-side">STRONG FOUNDATIONS. GREATER POSSIBILITIES.</div></section>
 <div className="values-strip"><span>BUILT ON WHAT MATTERS</span><div><Check/>Quality craftsmanship</div><div><Check/>Safety at every step</div><div><Check/>Transparent partnership</div><div><Check/>Purposeful execution</div></div>
 <section id="about" className="section about reveal"><div className="eyebrow"><span/>THE SHANE DIFFERENCE</div><div className="about-content"><h2>Great buildings start<br/>with <span>great partnerships.</span></h2><div><p>Behind every space is a vision. At Shane Construction Corporation, we bring that vision into focus—with thoughtful planning, skilled craftsmanship, and a commitment to getting the details right.</p><p>From homes to commercial spaces, we build with you, for you, and for what comes next.</p><a className="text-link" href="#process">Get to know our approach <ArrowUpRight size={19}/></a></div></div></section>
 <section id="services" className="services section"><div className="section-heading reveal"><div><div className="eyebrow"><span/>WHAT WE DO</div><h2>From the ground up.<br/><span>We’ve got you covered.</span></h2></div><a className="text-link" href="#contact">Find your building solution <ArrowUpRight size={20}/></a></div><div className="service-grid">{services.map((s,i)=><a className="service-card reveal" href="#contact" key={s.title}><div className="service-top"><s.icon size={32} strokeWidth={1.3}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.text}</p><ArrowUpRight className="service-arrow" size={23}/></a>)}</div></section>
 <section id="projects" className="section projects"><div className="section-heading reveal"><div><div className="eyebrow"><span/>SPACES THAT INSPIRE</div><h2>A vision of <span>what’s possible.</span></h2></div><p>Explore a few directions for your next build.<br/>Concept imagery, endless possibilities.</p></div><div className="filters" role="group" aria-label="Filter project concepts">{['All projects','Residential','Commercial','Renovation'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}{f==='All projects'&&<span>03</span>}</button>)}</div><div className="project-grid">{projects.filter(p=>filter==='All projects'||p.category===filter).map((p,i)=><button className="project-card" onClick={()=>setSelected(p)} key={p.name}><div className="project-image"><img src={photo(p.image,1000)} alt={p.name} loading="lazy"/><span className="project-tag">{p.category}</span><span className="project-open"><ArrowUpRight/></span></div><div className="project-title"><h3>{p.name}</h3><span>0{projects.indexOf(p)+1}</span></div><p>Design inspiration · Concept showcase</p></button>)}</div></section>
 <section className="commitment"><div className="commitment-image"><img src={photo('photo-1503387762-592deb58ef4e',1200)} alt="Architectural plans prepared for a construction project" loading="lazy"/><span className="image-caption">PRECISION IN EVERY DETAIL.</span></div><div className="commitment-copy reveal"><div className="eyebrow light"><span/>MORE THAN CONSTRUCTION</div><h2>Your ambition.<br/>Our commitment.<br/><em>A stronger future.</em></h2><p>We believe the best results come from doing the fundamentals well. Listening closely. Planning carefully. Building responsibly. And standing behind the work.</p><a href="#contact" className="button orange">Let’s talk about your vision <ArrowUpRight size={20}/></a></div></section>
 <section id="process" className="section process"><div className="section-heading reveal"><div><div className="eyebrow"><span/>A CLEAR PATH FORWARD</div><h2>Big ideas. <span>Solid execution.</span></h2></div><p>From our first conversation to your final walkthrough,<br/>know what comes next.</p></div><div className="process-grid">{[['Discover','We listen to your goals, understand your space, and define what success looks like.'],['Plan','Together, we align the design, scope, budget, and timeline before work begins.'],['Build','We coordinate the people, materials, and details that bring your vision to life.'],['Deliver','A careful walkthrough and thoughtful handover, so you can enjoy your next chapter.']].map(([title,text],i)=><div className="reveal" key={title}><div className="step-number">0{i+1}<ArrowRight size={18}/></div><h3>{title}</h3><p>{text}</p></div>)}</div></section>
 <section className="section faq"><div><div className="eyebrow"><span/>GOOD QUESTIONS. CLEAR ANSWERS.</div><h2>Let’s lay<br/>the groundwork.</h2></div><div className="faq-list">{[['What kind of projects can we discuss?','We welcome inquiries about residential and commercial construction, design and build, renovations, fit-outs, and project management. Share your plans so we can discuss the right approach.'],['What should I prepare for our first conversation?','A location, a brief description of your vision, your preferred timeline, and an initial budget are a helpful start. Existing plans or reference photos are welcome, but you can begin with an idea.'],['How is a project estimate prepared?','An estimate depends on the scope, site conditions, design, materials, and schedule. These details should be reviewed together before a project-specific quotation is prepared.']].map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={19}/>:<Plus size={19}/>}</button>{faq===i&&<p id={`faq-${i}`}>{a}</p>}</div>)}</div></section>
 <section id="contact" className="section contact"><div><div className="eyebrow"><span/>YOUR NEXT CHAPTER STARTS HERE</div><h2>Have a vision?<br/>Let’s <em>build it.</em></h2><p>Tell us what you have in mind.<br/>Every great project starts with a conversation.</p><span className="contact-note">A strong foundation starts with you. <ArrowUpRight/></span></div><form ref={form} onSubmit={submit}><div className="form-row"><label>Your name<input name="name" placeholder="Juan Dela Cruz" autoComplete="name" required/></label><label>Email address<input name="email" type="email" placeholder="you@example.com" autoComplete="email" required/></label></div><label>What are you planning?<select name="type" required defaultValue=""><option value="" disabled>Select a project type</option><option>Residential construction</option><option>Commercial construction</option><option>Design & build</option><option>Renovation & fit-out</option><option>Project management</option></select></label><label>Tell us about your project<textarea name="message" placeholder="Your vision, location, and ideal timeline…" rows="3" required/></label><button className="button dark" type="submit">Prepare project inquiry <ArrowUpRight size={20}/></button><p className="form-note" role="status">{submitted?'Your inquiry has been downloaded. Keep it ready to share with the Shane team.':'Download your inquiry brief. Online delivery will be available once company contact details are added.'}</p></form></section>
 </main><footer><div className="footer-main"><Logo/><p>Strong foundations.<br/>Greater possibilities.</p><a href="#home">BACK TO TOP <ArrowUpRight size={18}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Shane Construction Corporation. All rights reserved.</span><span>BUILT WITH PURPOSE.</span></div></footer>
 <dialog ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null);}}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close project"><X/></button>{selected&&<><img src={photo(selected.image,1200)} alt={selected.name}/><div className="modal-content"><div className="eyebrow">{selected.category} / DESIGN CONCEPT</div><h2>{selected.name}</h2><p>{selected.description}</p><p className="form-note">Illustrative photography for inspiration; not a completed Shane Construction project.</p><a className="button orange" href="#contact" onClick={()=>setSelected(null)}>Discuss a similar project <ArrowUpRight size={18}/></a></div></>}</dialog></>;
}
createRoot(document.getElementById('root')).render(<App/>);
